version: "3.3"

services:
  database_nodejs_typescript:
    image: postgres
    container_name: database_nodejs_typescript
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=DMA39@braz
      - POSTGRES_DB=nodejs-with-typescript
    volumes:
      - pgdata:/data/postgres
  app:
    container_name: nodejs-with-typescript
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/user/app

volumes:
  pgdata:
    driver: local